"""Hook shell script content and settings.json configuration."""

HOOK_SCRIPT_CONTENT = '''#!/bin/sh
# AgentDiff hook -- pipes Claude Code event JSON to the local daemon.
# Generated by agentdiff init. Do not edit.
cat | curl -s --unix-socket "$CLAUDE_PROJECT_DIR/.agentdiff/daemon.sock" \\
  -X POST -H "Content-Type: application/json" \\
  -d @- http://localhost/event 2>/dev/null || true
'''


def get_hooks_config(hook_script_path: str) -> dict:
    """Return the hooks dict to merge into .claude/settings.json."""
    cmd = hook_script_path
    return {
        "hooks": {
            "PostToolUse": [
                {
                    "matcher": "Write|Edit",
                    "hooks": [{"type": "command", "command": cmd, "timeout": 5}],
                }
            ],
            "SessionStart": [
                {
                    "hooks": [{"type": "command", "command": cmd, "timeout": 5}],
                }
            ],
            "SubagentStart": [
                {
                    "hooks": [{"type": "command", "command": cmd, "timeout": 5}],
                }
            ],
            "SubagentStop": [
                {
                    "hooks": [{"type": "command", "command": cmd, "timeout": 5}],
                }
            ],
            "TaskCompleted": [
                {
                    "hooks": [{"type": "command", "command": cmd, "timeout": 5}],
                }
            ],
            "Stop": [
                {
                    "hooks": [{"type": "command", "command": cmd, "timeout": 5}],
                }
            ],
        }
    }
